trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: devops-1
  - name: aws_ecr_arn
    value: '427306808294.dkr.ecr.${AWS_REGION}.amazonaws.com'
  #  docker_image_tag: '$(Build.BuildId)'
  - name: ecr_repository_uri
    value: 427306808294.dkr.ecr.${AWS_REGION}.amazonaws.com/dev

stages:
- stage: BuildImage
  displayName: Build Nginx Docker Image
  jobs:
  - job: BuildNginxImage
    displayName: Build Nginx Docker Image
    steps:
    - script: |
        aws configure set aws_access_key_id "$(Access_key)"
        aws configure set aws_secret_access_key "$(Secret_access_key)"
      displayName: Configure AWS CLI

    - task: Docker@2
      displayName: Build Nginx image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        #buildContext: 'path/to/your/docker/context'
        repository: $(ecr_repository_uri)
        tags: |
          latest
          
- stage: PushImage
  displayName: Push Image to ECR
  dependsOn: BuildImage
  jobs:
  - job: PushImageToECR
    displayName: Push Image to ECR
    steps:
    - script: |
        aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin 427306808294.dkr.ecr.${AWS_REGION}.amazonaws.com"
      displayName: Login to ECR

    - script: |
        docker push 427306808294.dkr.ecr.${AWS_REGION}.amazonaws.com/dev
        
        #docker push ${aws_ecr_arn}/${project_env}/${module_name}:build-v${BUILD_NUMBER}
      displayName: Push image to ECR

